[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.9.0"

# Специальное правило для babel-polyfill - должно быть ПЕРЕД общим redirect
[[headers]]
  for = "/babel-polyfill-6.26.0.js"
  [headers.values]
    Content-Type = "application/javascript"

# Исключаем babel-polyfill из общего redirect
[[redirects]]
  from = "/babel-polyfill-6.26.0.js"
  to = "/babel-polyfill-6.26.0.js"
  status = 200

# Общий redirect для всех остальных файлов
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
